/*
 * This file is generated by jOOQ.
 */
package com.rinha.backend.infrastructure.database.model;


import com.rinha.backend.infrastructure.database.model.tables.Pessoas;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_SEARCH_TERM = Internal.createIndex(DSL.name("idx_search_term"), Pessoas.PESSOAS, new OrderField[] { Pessoas.PESSOAS.SEARCH_TERM }, false);
}
