/*
 * This file is generated by jOOQ.
 */
package com.rinha.backend.infrastructure.database.model;


import com.rinha.backend.infrastructure.database.model.tables.Pessoas;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.pessoas</code>.
     */
    public static final Pessoas PESSOAS = Pessoas.PESSOAS;
}
