micronaut:
  application:
    name: rinhaBackend2023Q3
  executors:
    io:
      type: fixed
      nThreads: 10

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/arena
    username: dbaccess
    password: pgsql
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
jpa:
  default:
    entity-scan:
      packages: com.rinha.backend.infrastructure
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        show-sql: true