micronaut:
  application:
    name: rinhaBackend2023Q3

datasources:
  hikari:
    url: ${DATABASE_URL:`jdbc:postgresql://localhost:5432/arena`}
    username: ${DATABASE_USER:dbaccess}
    password: ${DATABASE_PASSWORD:pgsql}
    db-type: postgres
    sql-dialect: POSTGRES
    maximum-pool-size: 75
    driver-class-name: org.postgresql.Driver
jpa:
  default:
    entity-scan:
      packages: com.rinha.backend.infrastructure

problem:
  enabled: true